### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by gwyrwch** [gwyrwch/course-work-5#1]
- [ ] Решения
1. Решения сохраняют ответ с комментарием для пометок в графике
2. Решения подсчитывают время работы/память
- [ ] Парсер тестов
1. EUC_2D
- [ ] Рисовалка графика
- [ ] Сравнение решений на метриках
- [ ] Возможность распараллеливания
- [ ] Многопоточный режим

**Comment by gwyrwch** [comment]
--comment
--show-last-results

**Comment by gwyrwch** [comment]
Методы решения:

- [ ] полный пербор (для маленьких входных данных)

- [ ] жадные алгоритмы(метод ближайшего соседа)

- [ ] метод минимального остовного дерева

- [ ] метод ветвей и границ

- [ ] муравьиный алгоритм

- [ ] генетический алгоритм

**Comment by gwyrwch** [comment]
Методы оптимизации:

- [ ]  Локальный поиск (оптимизация)

- [ ]  Метод имитации отжига

**Comment by gwyrwch** [comment]
**todo for 06.12** 

- [ ] запуск на всех тестах

- [ ] записывать полный маршрут в файл

- [ ] генетический алгоритм

- [ ] метод ветвей и границ

- [ ] рисовать решения (не от тестов) в юпитере
